export const members = [
    {
        name: "Reuben Devanesan",
        position: "Academic Secretary",
        ug: "Senior Undergraduate",
        branch: "Chemical Engineer",
        contact: "98676 08536",
        imgSrc: "./Images/Reuben Devanesan.webp",
        linkedin: "",
        www: "",
        email: "reuben.sd@iitgn.ac.in"
    },
    {
        name: "Yash Khandelwal",
        position: "Special Advisor",
        ug: "Senior Undergraduate",
        branch: "Chemical Engineer",
        contact: "",
        imgSrc: "./Images/Yash Khandelwal.webp",
        linkedin: "",
        www: "",
        email: "yash.khandelwal@iitgn.ac.in"
    },
    {
        name: "Kalash Kankaria",
        position: "Special Advisor",
        ug: "Senior Undergraduate",
        branch: "Chemical Engineer",
        contact: "93140 27008",
        imgSrc: "./Images/Kalash Kankaria.webp",
        linkedin: "",
        www: "",
        email: "kalash.kankaria@iitgn.ac.in"
    },
    {
        name: "Adit Rambhia",
        position: "Coordinator for Events & Initiatives",
        ug: "Senior Undergraduate",
        branch: "Chemical Engineer",
        contact: "93140 27008",
        imgSrc: "./Images/Adit profile.webp",
        linkedin: "",
        www: "",
        email: "rambhiaadit@iitgn.ac.in"
    },
    {
        name: "Aaryan Darad",
        position: "Coordinator for Events & Initiatives",
        ug: "Senior Undergraduate",
        branch: "Chemical Engineer",
        contact: "99985 83773",
        imgSrc: "./Images/AaryanDarad.webp",
        linkedin: "",
        www: "",
        email: "daradaaryan@iitgn.ac.in"
    },
    {
        name: "Vikash Kumar Beniwal",
        position: "Coordinator for Peer Assisted Learning",
        ug: "Senior Undergraduate",
        branch: "Chemical Engineer",
        contact: "",
        imgSrc: "./Images/VIKASH BENIWAL .webp",
        linkedin: "",
        www: "",
        email: "beniwalvikash@iitgn.ac.in"
    },
    {
        name: "Aditya Gupte",
        position: "Coordinator for Academic Discussion Hours",
        ug: "Senior Undergraduate",
        branch: "Chemical Engineer",
        contact: "96644 88377",
        imgSrc: "./Images/AdityaGupte.webp",
        linkedin: "",
        www: "",
        email: "adityaaditya@iitgn.ac.in"
    },
    {
        name: "Yash Ahire",
        position: "Coordinator for Class Representatives and Course Feedback",
        ug: "Senior Undergraduate",
        branch: "Chemical Engineer",
        contact: "72191 93716",
        imgSrc: "./Images/Yash Ahire.webp",
        linkedin: "",
        www: "",
        email: "yashahire@iitgn.ac.in"
    },
    {
        name: "Madhav Kanda",
        position: "Coordinator for Documentation & Outreach",
        ug: "Senior Undergraduate",
        branch: "Chemical Engineer",
        contact: "",
        imgSrc: "./Images/Madhav Kanda.webp",
        linkedin: "",
        www: "",
        email: "madhav.kanda@iitgn.ac.in"
    },
    {
        name: "Nishat Tatar",
        position: "Coordinator for Documentation & Outreach",
        ug: "Senior Undergraduate",
        branch: "Chemical Engineer",
        contact: "8530 32662",
        imgSrc: "./Images/index.webp",
        linkedin: "",
        www: "",
        email: "madhav.kanda@iitgn.ac.in"
    },
    {
        name: "Netram Choudhary",
        position: "Webmaster",
        ug: "Senior Undergraduate",
        branch: "Chemical Engineer",
        contact: "78771 92651",
        imgSrc: "./Images/NetramChoudhary.webp",
        linkedin: "",
        www: "",
        email: "choudharynetram@iitgn.ac.in"
    },
    {
        name: "Parth Govale",
        position: "Webmaster",
        ug: "Senior Undergraduate",
        branch: "Computer Science Engineer",
        contact: "96198 69044",
        imgSrc: "./Images/parth.webp",
        linkedin: "",
        www: "",
        email: "parth.govale@iitgn.ac.in"
    },
    {
        name: "Harsh Jain",
        position: "General Member",
        ug: "Senior Undergraduate",
        branch: "Material Science Engineer",
        contact: "98814 67068",
        imgSrc: "./Images/harsh.webp",
        linkedin: "",
        www: "",
        email: "harsh.jain@iitgn.ac.in"
    },
    {
        name: "Kritika Agarwal",
        position: "General Member",
        ug: "Senior Undergraduate",
        branch: "Material Science Engineer",
        contact: "",
        imgSrc: "./Images/noimg.webp",
        linkedin: "",
        www: "",
        email: "agarwalkritika@iitgn.ac.in"
    },
    {
        name: "Mayank Dahotre",
        position: "General Member",
        ug: "Senior Undergraduate",
        branch: "Material Science Engineer",
        contact: "",
        imgSrc: "./Images/noimg.webp",
        linkedin: "",
        www: "",
        email: "mayank.dahotre@iitgn.ac.in"
    },
    {
        name: "Athrava Bodhale",
        position: "General Member",
        ug: "Senior Undergraduate",
        branch: "Material Science Engineer",
        contact: "",
        imgSrc: "./Images/noimg.webp",
        linkedin: "",
        www: "",
        email: "atharva.bodhale@iitgn.ac.in"
    },
    {
        name: "Shrishti Mishra",
        position: "General Member",
        ug: "Senior Undergraduate",
        branch: "Material Science Engineer",
        contact: "92638 70017",
        imgSrc: "./Images/Shrishti Mishra.webp",
        linkedin: "",
        www: "",
        email: "shrishti.mishra@iitgn.ac.in"
    },
    {
        name: "Birudugadda Srivibhav",
        position: "General Member",
        ug: "Senior Undergraduate",
        branch: "Material Science Engineer",
        contact: "93925 39193",
        imgSrc: "./Images/Birudugadda Srivibhav.webp",
        linkedin: "",
        www: "",
        email: "birudugadda.srivibhav@iitgn.ac.in"
    },
    {
        name: "Birudugadda Srivibhav",
        position: "General Member",
        ug: "Senior Undergraduate",
        branch: "Material Science Engineer",
        contact: "93925 39193",
        imgSrc: "./Images/Birudugadda Srivibhav.webp",
        linkedin: "",
        www: "",
        email: "birudugadda.srivibhav@iitgn.ac.in"
    },
    {
        name: "Shrey Agarwal",
        position: "General Member",
        ug: "Senior Undergraduate",
        branch: "Material Science Engineer",
        contact: "",
        imgSrc: "./Images/noimg.webp",
        linkedin: "",
        www: "",
        email: "shrey.agarwal@iitgn.ac.in"
    },
    {
        name: "Ishan Agarwal",
        position: "General Member",
        ug: "Senior Undergraduate",
        branch: "Material Science Engineer",
        contact: "91188 86527",
        imgSrc: "./Images/Ishan Agarwal.webp",
        linkedin: "",
        www: "",
        email: "ishan.agarwal@iitgn.ac.in"
    },
]